services:
  php:
    build: .
    container_name: ${PROJECT_NAME}_php
    hostname: ${PROJECT_NAME}_php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    env_file:
      - .env
    command: tail -f /dev/null

  mysql:
    image: mysql/mysql-server:8.0
    container_name: ${PROJECT_NAME}_mysql
    hostname: ${PROJECT_NAME}_mysql
    ports:
      - 127.0.0.1:3306:3306
    env_file:
      - .env
    command: --socket=/tmp/mysql.sock

  rabbitmq:
    image: rabbitmq:3.12.2-management-alpine
    container_name: ${PROJECT_NAME}_rabbitmq
    hostname: ${PROJECT_NAME}_rabbitmq
    restart: always
    ports:
      - 127.0.0.1:15672:15672
    env_file:
      - .env